site_name: MeltyLand
site_description: Welcome to the meltyland
site_url: https://blog.meltyland.dev
repo_url: https://github.com/liulifox233/liulifox233.github.io
repo_name: liulifox233/liulifox233.github.io
edit_uri_template: "edit/main/docs/{path}"

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - navigation.expand
    - toc.follow
    - search.suggest
    - navigation.top
    - search.share
    - navigation.indexes
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - content.tabs.link
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - mkdocs-ja-ruby
  - blog:
      blog_toc: true
      blog_dir: .
      post_dir: "{blog}/posts"
      archive_date_format: MMMM YYYY
      archive_url_date_format: yyyy/MM
      post_date_format: full
      archive_toc: true
      categories_toc: true
      post_slugify: !!python/object/apply:ext.slugs.slugify
        kwds:
          short: true
  - blog:
      archive: false
      blog_toc: true
      blog_dir: records
      post_dir: "{blog}/posts"
      archive_date_format: MMMM YYYY
      archive_url_date_format: yyyy/MM
      post_date_format: full
      archive_toc: true
      categories_toc: true
      post_slugify: !!python/object/apply:ext.slugs.slugify
        kwds:
          short: true

extra:
  social:
    - icon: fontawesome/brands/github
      name: Ruri on Github
      link: https://github.com/liulifox233

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - def_list
  - tables
  - pymdownx.critic
  - toc:
      permalink: true
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - ext.chat

nav:
  - Posts:
    - index.md
  - Records:
    - records/index.md
  - Notes:
    - notes/index.md
    - database:
      - notes/database/cap.md
    - japanese:
      - notes/japanese/plan.md
      - notes/japanese/case-particles.md
  - About:
    - about.md

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/d3@7/dist/d3.min.js
  - javascripts/hpc-visualizations.js
  - javascripts/chat.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/hpc-visualizations.css
  - stylesheets/chat.css

copyright: <a href="https://icp.gov.moe/?keyword=20250039" target="_blank">萌ICP备20250039号</a>
