authors:
  ruri:
    name: 流离
    description: 誰も知らないところまで
    avatar: https://avatars.githubusercontent.com/u/88608708
  hare:
    name: 晴
    description: 暂时还不能被公开的情报
    avatar: https://avatars.githubusercontent.com/u/191038400